controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

info:
    path: /info
    controller: App\Controller\InfoController::mostrarInfo
    methods: GET

reservas_list:
    path: /reservas/{claveApi}
    controller: App\Controller\ReservaController::getAll
    methods: GET

reserva_show:
    path: /reservas/{claveApi}/{id}
    controller: App\Controller\ReservaController::getReserva
    methods: GET
    requirements:
        id: \d+

reserva_create:
    path: /reservas/{claveApi}
    controller: App\Controller\ReservaController::crearReserva
    methods: POST

reserva_update:
    path: /reservas/{claveApi}/{id}
    controller: App\Controller\ReservaController::modificarReserva
    methods: PUT
    requirements:
        id: \d+

reserva_delete:
    path: /reservas/{claveApi}/{id}
    controller: App\Controller\ReservaController::borrarReserva
    methods: DELETE
    requirements:
        id: \d+
